// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9j2ecvjE4UuoNQbQIViu_65bQoFbeBws',
    appId: '1:785964433867:web:edfa83a9a6397185cb764e',
    messagingSenderId: '785964433867',
    projectId: 'payansh-d5dd0',
    authDomain: 'payansh-d5dd0.firebaseapp.com',
    storageBucket: 'payansh-d5dd0.firebasestorage.app',
    measurementId: 'G-YJMEW52EHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQmX11gOCire0e-DbNhWd51-pYB4mB58o',
    appId: '1:785964433867:android:f9e9e896b69f24c8cb764e',
    messagingSenderId: '785964433867',
    projectId: 'payansh-d5dd0',
    storageBucket: 'payansh-d5dd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTH401g6hJXFXEAa5s8k_awtd-qVmu7sg',
    appId: '1:785964433867:ios:b2ccfc76563cad73cb764e',
    messagingSenderId: '785964433867',
    projectId: 'payansh-d5dd0',
    storageBucket: 'payansh-d5dd0.firebasestorage.app',
    iosBundleId: 'com.payansh.payansh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTH401g6hJXFXEAa5s8k_awtd-qVmu7sg',
    appId: '1:785964433867:ios:b2ccfc76563cad73cb764e',
    messagingSenderId: '785964433867',
    projectId: 'payansh-d5dd0',
    storageBucket: 'payansh-d5dd0.firebasestorage.app',
    iosBundleId: 'com.payansh.payansh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9j2ecvjE4UuoNQbQIViu_65bQoFbeBws',
    appId: '1:785964433867:web:96ebcd1c99291b07cb764e',
    messagingSenderId: '785964433867',
    projectId: 'payansh-d5dd0',
    authDomain: 'payansh-d5dd0.firebaseapp.com',
    storageBucket: 'payansh-d5dd0.firebasestorage.app',
    measurementId: 'G-2XGMZEX0XR',
  );
}
